services:
  - type: web
    name: hui-web
    env: node
    branch: master
    buildCommand: npm run install-all && npm run build
    startCommand: npm run server
    autoDeploy: true
    disk:
      name: uploads
      mountPath: api/uploads
      sizeGB: 5
